### ISSUE TITLE
Image removed from Dockerhub.

### ISSUE THREAD

**Issue by alex-gunning-jumo** [assemblyline/ok#3]
Hi there

It appears that your image has been removed from Dockerhub (probably automatically).

My company uses it though :) Could you push it back up there?

Kind regards

Alex

**Comment by errm** [comment]
Could you confirm the exact image/tag you are using?

**Comment by alex-gunning-jumo** [comment]
Yeah, sure. It's `quay.io/assemblyline/ok`

**Comment by errm** [comment]
I don't seem to have access to the quay.io repo mentioned in the README anymore, I think I handed it to someone at @reevoo when I stoped working there!

I am having a look if I can get it to build on dockerhub.

**Comment by alex-gunning-jumo** [comment]
Aah, okay. Darn. If you could it would be massive kudos. Otherwise it's okay, we can make another plan.

**Comment by errm** [comment]
I set up builds on docker hub so you should be able to use

`assemblyline/ok`

see: https://hub.docker.com/r/assemblyline/ok

**Comment by alex-gunning-jumo** [comment]
@errm Much much much appreciated. Thank you.

**Comment by errm** [comment]
Np
